// DO NOT EDIT THIS FILE !!!
// This file is automatically generated by CMake from coresponding .glsl file.

const char* fragment_literal = 
"#version 330 core\n"
"in vec3 fragment_pos;\n"
"in vec3 normal;\n"
"in vec2 texture_coord;\n"

"out vec4 Frag_color;\n"

"struct Light {\n"
"    vec3 position;\n"
"    vec3 color;\n"
"};\n"

"uniform Light light;\n"
"uniform sampler2D texture_diffuse1;\n"
"uniform vec3 color;\n"

"void main()\n"
"{\n"
"	vec3  norm = normalize(normal);\n"
"    vec3  light_dir = normalize(light.position - fragment_pos);\n"
"    float angle = max(dot(norm, light_dir), 0.0);\n"

"    vec3  diffuse = light.color * angle * color;\n"
"    // vec3  diffuse = light.color * angle * color + vec3(0.2, 0.2, 0.2) * color;\n"
"    // vec3  diffuse = light.color * angle * texture(texture_diffuse1, texture_coord).rgb;\n"

"    Frag_color = vec4(diffuse, 1.0);\n"
"}\n";