#include <string>
#include <fstream>

using namespace std;

int main(int argc, char* argv[])
{
    string infile_path(argv[1]);
    ifstream infile(infile_path);

    size_t delimiter = infile_path.find_last_of("/\\");
    string infile_name = infile_path.substr(delimiter+1);

    string outfile_name = infile_name.replace(infile_name.find(".glsl"), 5, "_literal");
    ofstream outfile(outfile_name + ".cpp");

    string line;
    outfile << "// DO NOT EDIT THIS FILE !!!\n";
    outfile << "// This file is automatically generated by CMake from coresponding .glsl file.\n\n";
    outfile << "const char* " + outfile_name + " = ";
    while (getline(infile, line))
    {
        outfile << '\n';
        if (!line.empty()) {
            outfile << "\"" << line << "\\n\"";
        }
    }
    outfile << ';';

    outfile.close();
    return 0;
}
