// DO NOT EDIT THIS FILE !!!
// This file is automatically generated by CMake from coresponding .glsl file.

const char* vertex_literal = 
"#version 330 core\n"
"out vec3 fragment_pos;\n"
"out vec3 normal;\n"
"out vec2 texture_coord;\n"

"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec3 aNormal;\n"
"layout (location = 2) in vec2 aTexCoords;\n"

"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"

"void main()\n"
"{\n"
"    fragment_pos = vec3(model * vec4(aPos, 1.0));\n"
"    normal = mat3(transpose(inverse(model))) * aNormal;\n"
"    texture_coord = aTexCoords;\n"

"    gl_Position = projection * view * model * vec4(aPos, 1.0f);\n"
"}\n";